name: "Build LazyChain 💤"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  GOFLAGS: '-buildvcs=false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build LazyChain
        run: make build