name: "Build Slothchain 💤"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Slothchain
        uses: ignite/cli/actions/cli@main
        with:
          args: chain build