name: "E2E Test LazyChain 💤"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lazychain
  LAZYCHAIN_IMAGE_REPOSITORY: ghcr.io/lazychain/lazychain
  LAZYCHAIN_IMAGE_VERSION: latest # TODO: It would be better to get a specific version of the image

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/lazychain/lazychain:latest # TODO: It would better to create a commit specific tag

  interchaintest:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: 'interchaintest/go.sum'

      - name: Load Docker Image
        run: docker pull ${{ env.LAZYCHAIN_IMAGE_REPOSITORY }}:${{ env.LAZYCHAIN_IMAGE_VERSION }}

      - name: Run interchaintest
        run: make interchaintest